# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/github-home" # the subpath of your site, e.g. /blog/
url: "https://github.ma-jones.com" # the base hostname & protocol for your site
permalink: /404.html

twitter_username:
github_username:

# Build settings
markdown: kramdown
