# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/github-home" # the subpath of your site, e.g. /blog/
url: "/github-home" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: electricool
